#!/bin/bash


DOMAIN="$2"
CERTS_DIR="./certs"
#echo $DOMAIN


openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
    -keyout $CERTS_DIR/cdn_key.pem -out $CERTS_DIR/cdn_cert.pem \
    -subj "/CN=$DOMAIN" \
    -addext "subjectAltName=DNS:$DOMAIN"

#openssl x509 -in $CERTS_DIR/cdn_cert.pem -text -noout

# echo "Certificate and private key generated for $DOMAIN"
# echo "Certificate: $CERTS_DIR/cdn_cert.pem"
# echo "Private Key: $CERTS_DIR/cdn_key.pem"
